all:
	cp -f parser.js ../releases
	cp -f parser.js ../releases/parser_commonjs.js
	cat commonjs_ending.txt >> ../releases/parser_commonjs.js
	cp -f parser.js ../releases/parser_module.js
	cat module_ending.txt >> ../releases/parser_module.js
