all:
	cat parser_fragment.js > ../releases/parser.js
	cat tree.js >> ../releases/parser.js
	cat strings.js >> ../releases/parser.js
	cat tree_viewer.js >> ../releases/parser.js
	cat module_ending.js >> ../releases/parser.js
	cd ../../.. && node index
